export const ROUTES = {
  HOME: '/',
  PRODUCT_DETAIL: '/product/:slug',
  CATEGORY: '/category/:id',
  SEARCH: '/search',
  ABOUT: '/about',
  CART: '/cart',
  WISHLIST: '/wishlist',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  GALLERY: '/gallery',
  LOGIN: '/login',
  REGISTER: '/register',
  FORBIDDEN: '/403',

  ADMIN: {
    ROOT: '/admin',
    DASHBOARD: '/admin',
    PRODUCTS: '/admin/products',
    CATEGORIES: '/admin/categories',
    EVENTS: '/admin/events',
    ORDERS: '/admin/orders',
    GALLERY: '/admin/gallery',
  },
} as const;